services:
  frontend:
    build: ./frontend/
    container_name: green_market
    ports:
      - "5173:5173"
    volumes:
      - ./:/frontend
      - /app/node_modules
  backend:
    build: ./backend/
    container_name: symfony_app
    volumes:
      - ./backend/:/var/www/html:delegated
      - /var/www/html/vendor
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
